### ISSUE TITLE
Data.js different from the one used in Delta 2.0

### ISSUE THREAD

**Issue by Aadil3393** [apna-college/wanderlust#5]
Dear Maintainers,

Hope you are doing well!

I wanted to bring to your notice that the data.js file that is being used is different from the one that is used Delta 2.0 course. The image property of the schema in course is set to type String and accepts a URL.Whereas in the file, Image property accepts an object and URL is a property of it.
Request you to please update the file so that there is no confusion while studying for future batches.

Thank you so much!
Aadil Mohan

data.js in repo
![image](https://github.com/apna-college/wanderlust/assets/108352440/da2a27ea-8ce9-4bce-a9b0-af508377ca7c)

data.js in tutorial
![image](https://github.com/apna-college/wanderlust/assets/108352440/88037690-8079-4305-91c3-25696edc762e)

**Comment by anuj-bhatia** [comment]
Thanks for reporting this issue i was scratching my head over it for the past few minutes myself thinking i made an error somewhere. 
**Fix for the issue:** I changed the schema in the listing.js file to match the data.js in the repo
 
![apna-college-schema-issue](https://github.com/apna-college/wanderlust/assets/140883024/5527ed97-aa8d-4605-8f88-5023474b5697)

**Comment by Aadil3393** [comment]
Thank you so much!

**Comment by Abhinandan-Sah** [comment]
I have just found the solution. There should be image of type: Object instead of type: String.  Hope, @apna-college and maintainers will solve this issue soon. So, that the student will not face any problem.
